/*
	@AUTHOR :- KAISER SAKHI
	@DATE :- 4/28/2021
	@ORACLE 10g
    
*/

ALTER TABLE STUDENT DROP CONSTRAINT FK_COURSE;
ALTER TABLE COURSE DROP CONSTRAINT PK_COURSE;

DROP TABLE STUDENT;
DROP TABLE COURSE;
