/*
	@AUTHOR :- KAISER SAKHI
	@DATE :- 4/28/2021
	@ORACLE 10g
    -NON-ANSI joins 
    
*/

SELECT A.ID S_ID, A.NAME st_name, B.NAME COURSE, B.CFEES FEES
FROM STUDENT A, COURSE B
WHERE A.COURSE_ID = B.CID;



SELECT A.ID S_ID, A.NAME st_name, B.NAME COURSE, B.CFEES FEES
FROM STUDENT A, COURSE B
WHERE A.COURSE_ID > B.CID;



SELECT A.ID S_ID, A.NAME st_name, B.NAME COURSE, B.CFEES FEES
FROM STUDENT A, COURSE B
WHERE FEES BETWEEN 10000 AND 20000;
