/*
	@AUTHOR :- KAISER SAKHI
	@DATE :- 4/15/2021
	@ORACLE 10g
*/

CREATE USER user1 IDENTIFIED BY user1;
CREATE USER user2 IDENTIFIED BY user2;
CREATE USER user3 IDENTIFIED BY user3;

GRANT CONNECT, RESOURCE TO user1;
GRANT CONNECT, RESOURCE TO user2;
GRANT CONNECT, RESOURCE TO user3;

GRANT CREATE SESSION TO user1 WITH ADMIN OPTION;
GRANT CREATE SESSION TO user2 WITH ADMIN OPTION;
GRANT CREATE SESSION TO user3 WITH ADMIN OPTION;

GRANT UNLIMITED TABLESPACE TO user1;
GRANT UNLIMITED TABLESPACE TO user1;
GRANT UNLIMITED TABLESPACE TO user3;

REVOKE UNLIMITED TABLESPACE FROM user1;
REVOKE UNLIMITED TABLESPACE FROM user2;
REVOKE UNLIMITED TABLESPACE FROM user3;

REVOKE CREATE SESSION FROM user1;
REVOKE CREATE SESSION FROM user2;
REVOKE CREATE SESSION FROM user3;

REVOKE CONNECT, RESOURCE FROM user1;
REVOKE CONNECT, RESOURCE FROM user2;
REVOKE CONNECT, RESOURCE FROM user3;


DROP USER user1 CASCADE;
DROP USER user2 CASCADE;
DROP USER user3 CASCADE;







