INSERT INTO student VALUES(101, 'Kaiser Sakhi', 'Kirkum', 'Jalandar', 'Punjab', 'India', '10-APR-2018');
INSERT INTO student VALUES(102, 'Tahir Sakhi', 'Jalout', 'Jalandar', 'Punjab', 'India', '10-JUN-2016');
INSERT INTO student VALUES(103, 'Imran Tahir', 'Malout', 'Kalandar', 'Punjab', 'India', '02-JAN-2015');
INSERT INTO student VALUES(104, 'Adil Manzoor', 'Kalout', 'Malandar', 'Punjab', 'India', '10-DEC-2019');
INSERT INTO student VALUES(105, 'Zahoor Ahamed', 'Andri', 'Palandar', 'Punjab', 'India', '01-NOV-2018');
INSERT INTO student VALUES(106, 'Masroor Imran', 'Jalabi Gali', 'Balandar', 'Punjab', 'India', '01-OCT-2018');
INSERT INTO student VALUES(107, 'Shahid Imran', 'New Ford', 'Illinio', 'Texas', 'America', '15-FEB-2017');
INSERT INTO student VALUES(108, 'Asrar Khan','New Ford', 'Illinio', 'Texas', 'America', '15-FEB-2017');
INSERT INTO student VALUES(109, 'Javid Ahmad', 'Ruther Ford Street', 'Capsicum', 'Texas', 'America', '15-MAR-2016');
INSERT INTO student VALUES(110, 'Ali', 'Kitkat Street-1', 'Illinio', 'Texas', 'America', '15-JUL-2016');
