CREATE TABLE student(
    st_rollno NUMBER(6),
    st_name VARCHAR2(30) CONSTRAINT NN_NAME_STUDENT NOT NULL, 
    st_address VARCHAR(35) CONSTRAINT NN_ADDRESS_STUDENT NOT NULL,
    CONSTRAINT PK_STUDENT1 PRIMARY KEY (st_rollno)
);

CREATE TABLE student_detail(
    st_rollno NUMBER(6),
    st_date DATE CONSTRAINT NN_DATE_STUDENT_DETAIL NOT NULL,
    st_present_absent VARCHAR2(1) CONSTRAINT NN_PRESENT_AB_STUDENT_DETAIL NOT NULL,
    CONSTRAINT FK_STUDENT_DETAIL FOREIGN KEY (st_rollno) REFERENCES student(st_rollno) ON DELETE CASCADE
);

SELECT constraint_name, table_name FROM user_constraints WHERE table_name = 'STUDENT';
SELECT constraint_name, table_name FROM user_constraints WHERE table_name = 'STUDENT_DETAIL';



INSERT INTO STUDENT VALUES(1, 'Kaiser Sakhi', 'colony');

INSERT INTO student_detail VALUES( 1, '02-NOV-1989', 'P' );

SET LINESIZE 150;

SELECT * FROM STUDENT S, STUDENT_DETAIL SD WHERE S.st_rollno = SD.st_rollno;

DELETE FROM STUDENT WHERE st_rollno = 1;

SELECT * FROM STUDENT;
SELECT * FROM STUDENT_DETAIL;





ALTER TABLE STUDENT_DETAIL DROP CONSTRAINT FK_STUDENT_DETAIL;
ALTER TABLE student DROP CONSTRAINT PK_STUDENT1;
ALTER TABLE student DROP CONSTRAINT NN_NAME_STUDENT;
ALTER TABLE student DROP CONSTRAINT NN_ADDRESS_STUDENT;


ALTER TABLE STUDENT_DETAIL DROP CONSTRAINT NN_DATE_STUDENT_DETAIL;
ALTER TABLE STUDENT_DETAIL DROP CONSTRAINT NN_PRESENT_AB_STUDENT_DETAIL;

DROP TABLE STUDENT_DETAIL;
DROP TABLE STUDENT;


